---
abstract: 'Query pod documents'
author:
  - 'Tim Potapov <tim.potapov[AT]gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Query
provides:
  Pod::Query:
    file: lib/Pod/Query.pm
    version: '0.36'
requires:
  Pod::LOL: '0.08'
  Role::Tiny: '2.002004'
  Term::Size::Any: '0.002'
  perl: '5.024'
resources:
  bugtracker: https://github.com/poti1/pod-query/issues
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: https://github.com/poti1/pod-query
version: '0.36'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
